### ISSUE TITLE
Make build error

### ISSUE THREAD

**Issue by PiotrFerenc** [openbankit/docker-node#1]
after `sudo make build`  

```
...
Getting golang.org/x/crypto/ssh/terminal
fatal: reference is not a tree: ff4a55a20a86994118644bbddc6a216da193cc13
Getting golang.org/x/net/context
Getting golang.org/x/net/http2
Getting golang.org/x/net/netutil
Getting gopkg.in/gorp.v1
Getting gopkg.in/tylerb/graceful.v1
Getting gopkg.in/yaml.v2
FATAL: command "restore" failed: could not retrieve dependency: exit status 128
FATAL: command "vendor" failed: exit status 1
ERROR: Service 'horizon' failed to build: The command '/bin/sh -c gb vendor restore' returned a non-zero code: 1
Makefile:17: polecenia dla obiektu 'build' nie powiodły się
make: *** [build] Błąd 1
```

system:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

plz  help me
https://travis-ci.org/stellar/horizon/jobs/350571522#L601

**Comment by PiotrFerenc** [comment]
wrong commit in no-debug replace ff4a55a20a86994118644bbddc6a216da193cc13 to bfacf9d8a444b50f5d7ae47727544e775486966f

**Comment by ymann** [comment]
Hi, I am encountering the same issue. Could you please elaborate on how you fixed this bug?

**Comment by MehdiSE** [comment]
Hi, ymann
in the file /vhosts/docker-node/docker/horizon/Dockerfile, right before  the line "RUN gb vendor restore", 
add the following line
RUN sed -i "s/ff4a55a20a86994118644bbddc6a216da193cc13/bfacf9d8a444b50f5d7ae47727544e775486966f/g" /vhosts/horizon/vendor/manifest
this will update the manifest file with the right reference given by PiotrFerenc
